version: '3.8'
services:
  web:
    container_name: news-crawler
    build: .
    ports:
      - "8000:8000"
    env_file: 
      - .env
    networks:
      - ansor-network

networks:
  ansor-network:
    external: true
